name: Add new stamps

on: 
  push:
    branches:
    - main
  schedule:
  - cron: "0 14 * * *"
  workflow_dispatch:

jobs:
  add-new-stamps:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repository
      uses: actions/checkout@v2
      with:
        path: data
        ref: main
        fetch-depth: 0
    - name: Checkout helper scripts repository
      uses: actions/checkout@v2
      with:
        repository: gwisp2/stamp-finder-monorepo
        path: sf
    - name: Install helper scripts
      run: pushd sf/backend && ./setup.py install --user && popd
    - name: Find new stamps
      run: '"/home/runner/.local/bin/sf" stamps scrape-new --db=./data'
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        path: data
        title: Automatic parser discovered new stamps.
        body: See commit for more information.
        commit-message: Automatic parser discovered new stamps.
        delete-branch: true
