name: Check rusmarka for new stamps

on: 
  push:
    branches:
    - main
  schedule:
  - cron: "0 14 * * *"
  workflow_dispatch:

jobs:
  scrape-new-stamps:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repository
      uses: actions/checkout@v3
      with:
        path: data
    - name: Download sfscrape
      run: wget https://github.com/gwisp2/stamp-finder-monorepo/releases/latest/download/sfscrape && chmod +x sfscrape
    - name: Scrape new stamps
      run: ./sfscrape -n ./data
    - name: Create pull request if something changed
      uses: peter-evans/create-pull-request@v3
      with:
        path: data
        title: Automatic parser discovered new stamps.
        body: See commit for more information.
        commit-message: Automatic parser discovered new stamps.
        delete-branch: true
