name: Check rusmarka for new stamps

on: 
  push:
    branches:
    - main
  schedule:
  - cron: "0 14 * * *"
  workflow_dispatch:

jobs:
  scrape-new-stamps:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repository
      uses: actions/checkout@v3
      with:
        path: data
    - name: Checkout tools
      uses: actions/checkout@v3
      with:
        repository: gwisp2/stamp-finder-monorepo
        path: sf
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Install libvips
      run: sudo apt-get update && sudo apt-get install -y libvips-dev
    - name: Build tools
      run: pushd sf/tools && go build -buildvcs=false ./cmd/sfscrape && popd
    - name: Scrape new stamps
      run: sf/tools/sfscrape -n ./data
    - name: Create pull request if something changed
      uses: peter-evans/create-pull-request@v3
      with:
        path: data
        title: Automatic parser discovered new stamps.
        body: See commit for more information.
        commit-message: Automatic parser discovered new stamps.
        delete-branch: true
