name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: prod
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repository
      uses: actions/checkout@v2
      with:
        path: data
    - name: Checkout helper scripts repository
      uses: actions/checkout@v2
      with:
        repository: gwisp2/stamp-finder-scripts
        path: scripts
    - name: Install helper scripts
      run: pushd scripts && ./setup.py install --user && popd
    - name: Resize stamp images
      run: '"/home/runner/.local/bin/sfs" resize-images --datadir=./data --size 232'
    - name: Update present field
      run: '"/home/runner/.local/bin/sfs" update-present-field --datadir=./data'
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
        config: ${{ secrets.SSH_CONFIG }} 
        if_key_exists: fail
    - name: Rsync over ssh
      run: rsync -r --exclude=".*" data/ prod:webroot/data --delete &>/dev/null
  